faculty:
    path:     /
    defaults: { _controller: "BruvinskyHighschoolBundle:Faculty:index" }

faculty_show:
    path:     /{id}/show
    defaults: { _controller: "BruvinskyHighschoolBundle:Faculty:show" }

faculty_new:
    path:     /new
    defaults: { _controller: "BruvinskyHighschoolBundle:Faculty:new" }

faculty_create:
    path:     /create
    defaults: { _controller: "BruvinskyHighschoolBundle:Faculty:create" }
    methods:  POST

faculty_edit:
    path:     /{id}/edit
    defaults: { _controller: "BruvinskyHighschoolBundle:Faculty:edit" }

faculty_update:
    path:     /{id}/update
    defaults: { _controller: "BruvinskyHighschoolBundle:Faculty:update" }
    methods:  [POST, PUT]

faculty_delete:
    path:     /{id}/delete
    defaults: { _controller: "BruvinskyHighschoolBundle:Faculty:delete" }
    methods:  [POST, DELETE]
