region:
    path:     /
    defaults: { _controller: "BruvinskyHighschoolBundle:Region:index" }

region_show:
    path:     /{id}/show
    defaults: { _controller: "BruvinskyHighschoolBundle:Region:show" }

region_new:
    path:     /new
    defaults: { _controller: "BruvinskyHighschoolBundle:Region:new" }

region_create:
    path:     /create
    defaults: { _controller: "BruvinskyHighschoolBundle:Region:create" }
    methods:  POST

region_edit:
    path:     /{id}/edit
    defaults: { _controller: "BruvinskyHighschoolBundle:Region:edit" }

region_update:
    path:     /{id}/update
    defaults: { _controller: "BruvinskyHighschoolBundle:Region:update" }
    methods:  [POST, PUT]

region_delete:
    path:     /{id}/delete
    defaults: { _controller: "BruvinskyHighschoolBundle:Region:delete" }
    methods:  [POST, DELETE]
