subject:
    path:     /
    defaults: { _controller: "BruvinskyHighschoolBundle:Subject:index" }

subject_show:
    path:     /{id}/show
    defaults: { _controller: "BruvinskyHighschoolBundle:Subject:show" }

subject_new:
    path:     /new
    defaults: { _controller: "BruvinskyHighschoolBundle:Subject:new" }

subject_create:
    path:     /create
    defaults: { _controller: "BruvinskyHighschoolBundle:Subject:create" }
    methods:  POST

subject_edit:
    path:     /{id}/edit
    defaults: { _controller: "BruvinskyHighschoolBundle:Subject:edit" }

subject_update:
    path:     /{id}/update
    defaults: { _controller: "BruvinskyHighschoolBundle:Subject:update" }
    methods:  [POST, PUT]

subject_delete:
    path:     /{id}/delete
    defaults: { _controller: "BruvinskyHighschoolBundle:Subject:delete" }
    methods:  [POST, DELETE]
