<?php

namespace Bruvinsky\HighschoolBundle\Entity;

/**
 * UniRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UniRepository extends \Doctrine\ORM\EntityRepository
{
}
