Bruvinsky\HighschoolBundle\Entity\Uni:
    type: entity
    table: uni
    repositoryClass: Bruvinsky\HighschoolBundle\Entity\UniRepository
    indexes:
        IDX_626BEC7CA67B1E36:
            columns:
                - id_city
    id:
        id:
            type: decimal
            nullable: false
            precision: 20
            scale: 0
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        name:
            type: string
            nullable: true
            length: 250
            options:
                fixed: false
    manyToOne:
        idCityUni:
            targetEntity: City
            cascade: {  }
            fetch: LAZY
            inversedBy: uniescities
            joinColumns:
                id_city:
                    referencedColumnName: id
            orphanRemoval: false
    oneToMany:
        classrooms:
            targetEntity: Classroom
            cascade: {  }
            fetch: LAZY
            mappedBy: idUniClass
        faculties_u:
            targetEntity: Faculty
            cascade: {  }
            fetch: LAZY
            mappedBy: idUni
    lifecycleCallbacks: {  }
